Description: >
    Carlos Mendez / Udacity DevOps Engineering Nano-Degree
    This template deploys a VPC (Virtual Private Cloud) on AWS.

Resources:
    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 10.0.0.0/16
            EnableDnsHostnames: true